services:
  influxdb:
    image: docker.io/bitnami/influxdb:2
    restart: unless-stopped
    ports:
      - 8086:8086
    env_file: ".env"
    volumes:
      - influxdb_data:/bitnami/influxdb

  grafana-init:
    image: busybox
    restart: no
    command: ["/bin/sh", "/script/init.sh"]
    volumes:
      - bitnami_grafana:/grafana
      - ./grafana-init:/script

  grafana:
    image: docker.io/bitnami/grafana:11
    restart: unless-stopped
    depends_on:
      grafana-init: 
        condition: service_completed_successfully
    ports:
      - 3000:3000
    env_file: ".env"
    volumes:
      - bitnami_grafana:/opt/bitnami/grafana

  stats-harvester:
    build:
      context: ./py-harvester
    restart: unless-stopped
    env_file: ".env"
    depends_on:
      - influxdb
    links:
      - influxdb

volumes:
  influxdb_data:
    driver: local
  bitnami_grafana:
    driver: local