services:
  influxdb:
    image: docker.io/bitnami/influxdb:2
    restart: unless-stopped
    ports:
      - 8086:8086
    env_file: "influxdb.env"
    volumes:
      - influxdb_data:/bitnami/influxdb

  grafana:
    image: docker.io/bitnami/grafana:11
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file: "grafana.env"
    volumes:
      - grafana_data:/opt/bitnami/grafana/data

  stats-harvester:
    build:
      context: ./py-harvester
    restart: unless-stopped
    env_file: "stats-harvester.env"
    depends_on:
      - influxdb
    links:
      - influxdb

volumes:
  influxdb_data:
    driver: local
  grafana_data:
    driver: local